### ISSUE TITLE
Only add tentative tests

### ISSUE THREAD

**Issue by annevk** [WICG/private-network-access#113]
I noticed a test got added for a feature defined here to `fetch/api/basic/request-forbidden-headers.any.js` that's not separated out as `tentative`.

**Comment by johnathan79717** [comment]
Makes sense.  Now tracked in https://bugs.chromium.org/p/chromium/issues/detail?id=1484509

**Comment by johnathan79717** [comment]
Fixed by https://github.com/web-platform-tests/wpt/pull/42054

**Comment by annevk** [comment]
Thanks!
