### ISSUE TITLE
The term "non-fetch requests" is confusing

### ISSUE THREAD

**Issue by domenic** [WICG/private-network-access#129]
Referring to https://github.com/WICG/private-network-access/blob/main/permission_prompt/explariner_non-fetch_requests.md

"non-fetch requests" implies to me requests that don't go through https://fetch.spec.whatwg.org/. However, there are supposed to be no such requests on the web platform.

The ones this document mentions

> it doesn't handle iframes or HTML src attributes

definitely go through fetch: for iframes it is https://html.spec.whatwg.org/#create-navigation-params-by-fetching step 19.5, and e.g. for img src it is https://html.spec.whatwg.org/#update-the-image-data step 26.

Because of this foundational issue, I'm not sure what this explainer is attempting to accomplish.

**Comment by johnathan79717** [comment]
This explainer is for fetches that were not initiated by the [Fetch API](https://fetch.spec.whatwg.org/#fetch-api) which therefore don't currently have a way to pass in the `targetAddressSpace`.  However, I can totally see why it's confusing.  Maybe call them "non-API fetches"?  Or any other name suggestions?

**Comment by domenic** [comment]
Non-API fetches is pretty reasonable!

**Comment by iVanlIsh** [comment]
Thanks for the advise!
I'm thinking about `Content Security Policy for Private Network Access Permission to relax mixed content`. Will that look more straightforward?

**Comment by domenic** [comment]
As long as the term "non-fetch requests" is fixed in the body, I don't think the title matters that much for me.
