### ISSUE TITLE
Feature detection

### ISSUE THREAD

**Issue by phistuck** [WICG/private-network-access#21]
I am not sure why the feature detection section exists.
Do you envision websites not showing links that would be blocked by this feature (due to non-cooperating local/private websites)?
If you still think it is needed, then I think it should be a boolean or something similar - `isLocalMixedContentProtectionSupported` (the name is not important).

I feel like this local/private/public distinction, is a privacy breach. While it does not tell the client side the exact IP of the website it is currently running in, it does distinguish itself between the local network/Intranet, private network and the Internet, which could be made useful for (attacks? spoofs? or) blocking features for, say, users that cloned public pages into their private/local networks.

Will a HOSTS-specified www.google.com that resolves to 10.0.12.12 return "private"?
Will "private" have CORS-rfc1918-free access to other "private" hosts?

This is not something I would want to expose to the client. I feel like it is none of its business.

**Comment by letitz** [comment]
I believe the feature detection section exists at least in part because of https://w3ctag.github.io/design-principles/#feature-detect, though that could be remediated with some kind of boolean indicating that private network requests are subject to enhanced scrutiny. @mikewest for historical insight.

I am not sure how this is a privacy breach and I am curious to explore this further. Web servers already know the IP address and interface over which a client contacted them. Even though that information might not be available at the web platform level, it might be reason enough to consider this *no worse*? Not sure how that interacts with IP blindness and the like.

To your questions:

> Will a HOSTS-specified www.google.com that resolves to 10.0.12.12 return "private"?

Yes.

> Will "private" have CORS-rfc1918-free access to other "private" hosts?

Yes. See also https://github.com/WICG/cors-rfc1918/pull/1, which raised the idea of subjecting all cross-origin requests targeting local/private IPs to CORS-RFC1918 checks.

**Comment by letitz** [comment]
After filling in the TAG's security and privacy self-review questionnaire ([here](https://github.com/WICG/cors-rfc1918/blob/master/security_privacy_self_review.md)) I am inclined to think this aspect of the spec is not pulling its weight.

**Comment by letitz** [comment]
I think the ordering here is to leave the IDL in the spec until Blink and WPT stop depending on it, then remove it. In the meantime I can add a banner to the HTML integration section explaining that this part is going away.

**Comment by jonathanKingston** [comment]
I'm being lazy here but is it common to have a property hang off Document and WorkerGlobalScope?

Isn't the usual extension point navigator if they're shared; why not WindowOrWorkerGlobalScope?

**Comment by annevk** [comment]
It is, but not having a property as suggested seems even better.

**Comment by jonathanKingston** [comment]
> It is, but not having a property as suggested seems even better.

Better? Surely consistency with `window.crossOriginIsolated` is worthwhile?

Perhaps there is rationale I'm not understanding though :)

**Comment by annevk** [comment]
As in, my understanding of https://github.com/WICG/private-network-access/issues/21#issuecomment-728355670 is that the plan is to remove this entirely.

**Comment by letitz** [comment]
Anne's right. I want to remove this from the spec.

**Comment by letitz** [comment]
Blink has its own version of the IDL: https://source.chromium.org/chromium/chromium/src/+/main:third_party/blink/renderer/core/dom/document.idl;l=182;drc=759e84c17afddffd440315069801e280d7ca1d31

I removed the references to the automatically-extracted IDL from WPTs a while ago. I'll go ahead and delete this section.

**Comment by fred-wang** [comment]
@letitz This attribute is still mentioned on the explainer: https://github.com/WICG/private-network-access/blob/main/explainer.md#integration-with-html  ; maybe that should be updated to with similar "A previous version of this specification proposed adding an addressSpace enum property" text.

**Comment by fred-wang** [comment]
and here too https://github.com/WICG/private-network-access/blob/main/explainer.md#remove-addressspace-idl

**Comment by fred-wang** [comment]
and at several places of https://github.com/WICG/private-network-access/blob/main/security_privacy_self_review.md

**Comment by letitz** [comment]
Thanks @fred-wang for catching those omissions. Re-opening to track fixing those references.
