### ISSUE TITLE
Name

### ISSUE THREAD

**Issue by annevk** [WICG/private-network-access#34]
As @mikewest mentioned this could probably do with a better name. As it's not really CORS and it might not really be RFC1918 anymore either, at least not exclusively.

"Preflights for local and private IP addresses"?

I suspect eventually most of this might end up in Fetch/HTML so maybe it doesn't matter that much...

**Comment by letitz** [comment]
That's a fair point, the current name does not seem to convey intent very clearly either judging from conversations I've had.

Some suggestions:
 - Private Network Access
 - Private Network Isolation
 - Private Network Request Blocking
 - Similarly with Cross Network ...

Nothing terribly inspired...

**Comment by annevk** [comment]
Private Network Access seems reasonable.

**Comment by letitz** [comment]
The repo has been renamed. I need to go through the spec text and fix it too.

**Comment by letitz** [comment]
Fixed by 3d8fb4fdee8a296a852e7eeab39fd747771411e4.
