### ISSUE TITLE
WebSockets integration

### ISSUE THREAD

**Issue by annevk** [WICG/private-network-access#40]
I looked at "Integration with WebSockets" and it did not do what I thought it would. In fact, I would have expected there to be no such section as WebSockets invokes fetch. This section patches the WebSocket handshake and I guess does not want a preflight to happen (but I think one still will due to the other modifications of fetch). I would prefer if WebSockets resulted in a preflight due to using fetch and was not otherwise modified.

Though see also discussion in https://github.com/whatwg/html/issues/3062 about reluctance from Chrome engineers to add preflight support for WebSockets...

This relates to #32, but also seems separate enough.

cc @ricea

**Comment by ricea** [comment]
See also #14.

I think it will probably require a heroic effort to implement preflight for WebSockets in Chrome, but without it there will be a massive hole in the protection, so it can't be helped.

**Comment by ricea** [comment]
Good news. I spoke with @yutakahirano who wrote the latest CORS implementation for Chrome. He doesn't think it will be too hard to implement preflights for WebSockets.

**Comment by letitz** [comment]
That's good news indeed!

I have no particular opinion about preflights vs handshake headers.

In the headers case, I appreciate the heads up that we need some work on the fetch integration to prevent websockets from also sending a preflight. In the preflight case, I am glad to hear that it should not be as hard as previously anticipated.

@ricea, do you share Anne's inclination towards preflights over handshake headers?

**Comment by letitz** [comment]
Thinking about this some more, I think preflights are the way to go. Simply adding headers would not be enough since the handshake includes headers with both credentials and attacker-controlled values (see #14).

Subsuming this issue into #14.

**Comment by mvduin** [comment]
> Subsuming this issue into whatwg/html#14.

Ehh, this currently references a pull request that appears to be completely unrelated to the topic of this thread. Did this previously point to something different?

(I was wondering if there's any update on Private Network Access restrictions for WebSockets, since it seems there's currently still no restriction, warning, or even a CORS preflight for (non-secure) public-to-private websocket connections, and I've not been able to find any info about the status or planning for this.)

**Comment by annevk** [comment]
I think #14 was meant.

Though the references in OP went bogus as well, not sure what's up.

**Comment by letitz** [comment]
I believe #14 was meant indeed. I wonder if things went sideways when the repo was renamed (either the first or second time)...
