### ISSUE TITLE
User consent

### ISSUE THREAD

**Issue by annevk** [WICG/private-network-access#42]
Is Chrome planning on implementing https://wicg.github.io/private-network-access/#user-mediation? How would the user make an informed decision here?

I had somehow missed this was in there until @martinthomson pointed it out in https://github.com/w3ctag/design-reviews/issues/572#issuecomment-810782778.

**Comment by mikewest** [comment]
With the caveat that I'll defer to @letitz here, both on sanity and priority, I don't think it's crazy to create a user-facing permission (whether or not we expose it through a dialog). I'm hopeful that we can learn from other platforms' experience here. I'm not a huge fan of iOS' "find and connect to local devices" dialog, but I don't think that means it's an impossible (or even bad) kind of question to ask.

**Comment by mikewest** [comment]
(It occurs to me that @tfpauly might have some insight here, given https://developer.apple.com/videos/play/wwdc2020/10110/).

**Comment by annevk** [comment]
Yeah, I certainly wouldn't want to discourage experimentation, but I don't think it's at all something that warrants a SHOULD at this point.

**Comment by letitz** [comment]
Good point. We have no plans to do so yet. My main concern with user mediation is that explaining the situation and the risks sounds hard. That being said, I am interested in exploring this with folks who know UX design better.

In RFC 2119 terms I guess this would fit best as `MAY` rather than `SHOULD`. WDYT?

**Comment by annevk** [comment]
Yeah, that works.

**Comment by mikewest** [comment]
How about [`MAY WISH TO`](https://tools.ietf.org/html/rfc6919#section-6)? :)
