### ISSUE TITLE
DRIVE-BY-PHARMING link is dead

### ISSUE THREAD

**Issue by fred-wang** [WICG/private-network-access#53]
https://wicg.github.io/private-network-access/#biblio-drive-by-pharming

redirects to https://www.broadcom.com/404-symantec

**Comment by letitz** [comment]
Paywalled version seems to live on at https://link.springer.com/chapter/10.1007/978-3-540-77048-0_38

**Comment by fred-wang** [comment]
Thanks, I can try to send a PR for this and the explainer too
