### ISSUE TITLE
IPv6

### ISSUE THREAD

**Issue by mnot** [WICG/private-network-access#6]
Loopback is `::1/128`; Link Local is `fe80::/10`. Reference is [RFC6890](https://tools.ietf.org/html/rfc6890).

Beyond that, I don't think you can do anything more than do some handwaving about discovering network status through other means (OS or otherwise), and allowing that information to influence the algorithm.

**Comment by martinthomson** [comment]
What about RFC 4193 (Unique local addresses)?

**Comment by mnot** [comment]
Aha, yes.

**Comment by annevk** [comment]
Seems this can be merged into #3.

**Comment by letitz** [comment]
I closed #3 since its main point seems to have been resolved. This issue on the other hand deserves a bit more consideration.

Re-posting Anne's comment from there over here FTR:

> It seems that https://tools.ietf.org/html/rfc4193 might provide RFC1918 for IPv6?

**Comment by letitz** [comment]
So far Chromium has been using existing code that determines whether an IPv6 address is "publicly-routable" to determine the address space. It does not seem like a great strategy to codify in a specification, but here it is for discussion at least:

 - `::1/128` -> `local`
 - IPv4-mapped address where the IPv4 address is public -> `public`
 - `2000::/3` -> `public`
 - `ff00://8` -> `public`
 - all others -> `private`

See [IsPublicRoutableIPv6()](https://source.chromium.org/chromium/chromium/src/+/master:net/base/ip_address.cc;l=92;drc=8f06f5aa76399529c5332f7c6adc68f95bd826b2).

**Comment by letitz** [comment]
At the very least, I would like the "all others" branch of the final algorithm to yield `public` so that failures to correctly classify a special case result in *less* privileges being afforded instead of *more*.

**Comment by letitz** [comment]
Of note: #29 concerns itself with reclassifying link-local IPv6 addresses as `private` instead of `local`.

**Comment by letitz** [comment]
I believe this issue is solved by #30, but I need to think about it a slight bit more before I close it officially.

**Comment by letitz** [comment]
I do believe this is addressed satisfactorily by #30. We now use the IANA registry to determine the address space of IPv6 addresses.
