### ISSUE TITLE
Private Network Access vs OAuth on localhost

### ISSUE THREAD

**Issue by theolivenbaum** [WICG/private-network-access#67]
Trying to understand what are the implications of the Private Network Access proposal for an OAuth2.0 flow happening on localhost (i.e. for a desktop app that needs to get authenticated with an online service and temporarily opens a localhost server to receive the oauth token from the service via a redirect).

The closest I could find to how OAuth works with localhost endpoints is https://wicg.github.io/private-network-access/#shortlinks, but it's not clear to me what if any would need to be changed.

**Comment by letitz** [comment]
The way it would work is as follows:

1. App starts a server on localhost:1234
2. App directs the user to https://auth.example, served by a public IP address
3. User logs in, https://auth.example redirects to http://localhost:1234/?token=secret
4. The browser notices a private network request (from `public` to `local`), so it sends a preflight request
5. Local server receives an `OPTIONS` request for `/?token=secret` with the following headers (among others):
   - `Access-Control-Request-Origin: https://auth.example`
   - `Access-Control-Request-Private-Network: true`
6. Local server checks the origin is as expected, then responds with `200 OK` and the following headers:
   - `Access-Control-Allow-Origin: https://auth.example`
   - `Access-Control-Allow-Private-Network: true`
7. The browser authorizes the request
8. Local server receives the `GET` request for `/?token=secret`, responds appropriately
9. User closes browser.

So the only changes are steps 4 to 7. Does that make sense?

See also https://developer.chrome.com/blog/private-network-access-preflight which explains some of this preflight business.

**Comment by theolivenbaum** [comment]
Thansk for the very detailed explanation @letitz!

Just to understand, the server on localhost now has to answer with: Access-Control-Allow-Private-Network: true

If that is not in the header, is the request blocked by default?

Thanks!

**Comment by letitz** [comment]
It has to respond with that header to the preflight request, yes. It also needs to reply with appropriate [CORS](https://developer.mozilla.org/en-US/docs/Web/HTTP/CORS) headers, just like for a regular CORS preflight request.
