### ISSUE TITLE
Mention cache poisoning attack

### ISSUE THREAD

**Issue by letitz** [WICG/private-network-access#74]
A public website can poison the cache for `http://myrouter.com/script.js`, which might then be loaded by the real private `http://myrouter.com`. The public website can thus elevate its PNA privileges and attack the private network. We should mention this in the spec's security considerations, though I do not think we should protect against this threat.

**Comment by annevk** [comment]
This is primarily a problem when there's no TLS, right? That already makes it kinda suspect.

**Comment by letitz** [comment]
Correct! HTTPS is really the right defense against this attack, but HTTPS on the private network is also very hard. In any case, we should note that this is a thing, but outside the threat model.

**Comment by annevk** [comment]
By the way, it would not be entirely absurd to make public/private part of the overall network keying story, which would entirely defeat this kind of attack.

**Comment by letitz** [comment]
What do you mean by network keying?

**Comment by annevk** [comment]
https://fetch.spec.whatwg.org/#network-partition-keys

There's other proposals such as https://wicg.github.io/anonymous-iframe/ that will also add keys there. Eventually all engines will need to have such infrastructure anyway so we might as well look into fixing this issue.

**Comment by letitz** [comment]
Ah, I see. I'm not opposed to it at first blush, and it might solve some problems around VPN usage / split horizon DNS, where the same website is sometimes public, sometimes private. Thanks for the suggestion!
