### ISSUE TITLE
Changes to Fetch: make Access-Control-Request-Private-Network a forbidden header name

### ISSUE THREAD

**Issue by jub0bs** [WICG/private-network-access#79]
The current specification's proposed changes to Fetch don't include the addition of `Access-Control-Request-Private-Network` to the list of so-called [_forbidden header names_](https://fetch.spec.whatwg.org/#forbidden-header-name).

However, since `Access-Control-Request-Headers` and `Access-Control-Request-Method` already are forbidden header names, I believe that `Access-Control-Request-Private-Network` should also become one, if only for consistency reasons.

**Comment by letitz** [comment]
I believe you are right! Thanks for filing the issue.
