### ISSUE TITLE
Why would an actual (non-preflight) request contain an Access-Control-Request-Private-Network header?

### ISSUE THREAD

**Issue by jub0bs** [WICG/private-network-access#80]
The following request can be found at the bottom of [example 3](https://wicg.github.io/private-network-access/#shortlinks):

```http
GET /short-links-are-short-after-shortening HTTP/1.1
Host: go
Access-Control-Request-Private-Network: true
...
Origin: https://mail.mega.corp
```

Perhaps I'm missing something, but I don't understand why that request would contain the `Access-Control-Request-Private-Network` header, since it's not a preflight request...

**Comment by letitz** [comment]
@mikewest might have had a threat in mind when he wrote this section?

You are right that in Chromium's current implementation, no-cors actual requests carry neither the `Access-Control-Request-Private-Network` nor `Origin` headers, unlike this example. In my view, there is no benefit to including them once the server has opted into receiving the request in its preflight response.

**Comment by mikewest** [comment]
This seems like a copy/paste error, removing it seems fine.

That said, I do think we considered something like  a precursor to the Fetch Metadata headers (`Sec-Fetch-*`) that would give servers contextual awareness that they're talking to someone outside their network when responding to requests. I don't think we ever defined it, but it might be worth considering. We certainly wouldn't spell it like this, though. :)

**Comment by letitz** [comment]
Got it, thanks! I'll remove the header from the example request.
